const {
  withAppBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  withGradleProperties,
  withMainApplication,
  withSettingsGradle,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SETTINGS_BLOCK = `
// @generated by withEdgezNative
include ':edgez-native'
project(':edgez-native').projectDir = new File(rootDir, '../native/edgez-android')`;

function addOnce(source, anchor, addition, description) {
  if (source.includes(addition.trim())) return source;
  const index = source.indexOf(anchor);
  if (index < 0) throw new Error(`Cannot add ${description}; missing anchor: ${anchor}`);
  return source.replace(anchor, `${anchor}${addition}`);
}

module.exports = function withEdgezNative(config) {
  config = withAndroidManifest(config, manifestConfig => {
    const application = manifestConfig.modResults.manifest.application[0];
    application.activity = application.activity || [];
    const upsertActivity = (name, attributes) => {
      let activity = application.activity.find(item => item.$['android:name'] === name);
      if (!activity) {
        activity = { $: { 'android:name': name } };
        application.activity.push(activity);
      }
      Object.assign(activity.$, attributes);
      return activity;
    };
    const expoTask = {
      'android:process': ':expo',
      'android:taskAffinity': '${applicationId}.expo',
      'android:excludeFromRecents': 'true',
    };
    const expoRuntimeActivity = upsertActivity('.ExpoRuntimeActivity', {
      ...expoTask,
      'android:exported': 'true',
      'android:launchMode': 'singleTask',
      'android:theme': '@style/Theme.App.SplashScreen',
    });

    // Development-client and custom app links must enter the isolated Expo
    // process. MainActivity intentionally retains only MAIN/LAUNCHER so a
    // remote Metro bundle can never replace the built-in DevTools home.
    const mainActivity = application.activity.find(
      item => item.$['android:name'] === '.MainActivity',
    );
    if (mainActivity?.['intent-filter']) {
      const hasAction = (filter, name) =>
        (filter.action || []).some(
          action => action.$['android:name'] === name,
        );
      const isViewFilter = filter =>
        hasAction(filter, 'android.intent.action.VIEW');
      const isLauncherFilter = filter =>
        hasAction(filter, 'android.intent.action.MAIN');
      const viewFilters = mainActivity['intent-filter'].filter(isViewFilter);
      const launcherFilters = mainActivity['intent-filter'].filter(isLauncherFilter);
      mainActivity['intent-filter'] = mainActivity['intent-filter'].filter(
        filter => !isViewFilter(filter) && !isLauncherFilter(filter),
      );
      mainActivity.$['android:exported'] = 'false';
      expoRuntimeActivity['intent-filter'] = [
        ...(expoRuntimeActivity['intent-filter'] || []),
        ...viewFilters,
      ];

      const nativeHomeActivity = upsertActivity(
        'ai.edgez.androiddevtools.MainActivity',
        {
          'android:exported': 'true',
          'android:launchMode': 'singleTask',
          'android:label': '@string/edgez_app_name',
          'android:theme': '@style/EdgezAppTheme',
          'tools:replace': 'android:exported',
        },
      );
      nativeHomeActivity['intent-filter'] = [
        ...(nativeHomeActivity['intent-filter'] || []),
        ...launcherFilters,
      ];
    }
    upsertActivity('expo.modules.devlauncher.launcher.DevLauncherActivity', expoTask);
    upsertActivity('expo.modules.devlauncher.compose.AuthActivity', expoTask);
    upsertActivity(
      'expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity',
      expoTask,
    );
    return manifestConfig;
  });

  config = withGradleProperties(config, gradleConfig => {
    const exists = gradleConfig.modResults.some(
      item => item.type === 'property' && item.key === 'edgezCmakeVersion',
    );
    if (!exists) {
      gradleConfig.modResults.push({
        type: 'property',
        key: 'edgezCmakeVersion',
        value: '3.22.1',
      });
    }
    return gradleConfig;
  });

  config = withSettingsGradle(config, gradleConfig => {
    gradleConfig.modResults.contents = addOnce(
      gradleConfig.modResults.contents,
      "include ':app'",
      SETTINGS_BLOCK,
      'the EdgeZ native Gradle project',
    );
    return gradleConfig;
  });

  config = withAppBuildGradle(config, gradleConfig => {
    let contents = addOnce(
      gradleConfig.modResults.contents,
      'react {',
      '\n    // EdgeZ DevTools is the built-in home, so include its JS in assembleDebug.\n    debuggableVariants = []',
      'embedded EdgeZ home bundling',
    );
    contents = addOnce(
      contents,
      'dependencies {',
      '\n    implementation project(\':edgez-native\')',
      'the EdgeZ native dependency',
    );
    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });

  config = withMainApplication(config, applicationConfig => {
    let contents = applicationConfig.modResults.contents;
    contents = addOnce(
      contents,
      'import com.facebook.react.common.ReleaseLevel',
      '\nimport ai.edgez.androiddevtools.EdgezNativePackage',
      'the EdgeZ package import',
    );
    contents = addOnce(
      contents,
      'PackageList(this).packages.apply {',
      '\n          add(EdgezNativePackage())',
      'the EdgeZ React package registration',
    );
    applicationConfig.modResults.contents = contents;
    return applicationConfig;
  });

  config = withDangerousMod(config, [
    'android',
    async modConfig => {
      const sourceDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app/src/main/java/ai/edgez/androiddevtools/runtime',
      );
      fs.mkdirSync(sourceDir, { recursive: true });
      fs.writeFileSync(
        path.join(sourceDir, 'ExpoRuntimeActivity.kt'),
        `package ai.edgez.androiddevtools.runtime

import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import expo.modules.ReactActivityDelegateWrapper

class ExpoRuntimeActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    setTheme(R.style.AppTheme)
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "main"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {}
    )
}
`,
      );
      return modConfig;
    },
  ]);

  return config;
};
