const {
  withAppBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  withGradleProperties,
  withMainApplication,
  withProjectBuildGradle,
  withSettingsGradle,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SETTINGS_BLOCK = `
// @generated by withEdgezNative
include ':edgez-native'
project(':edgez-native').projectDir = new File(rootDir, '../native/edgez-android')`;

const ORGANIC_MAPS_REPOSITORY = `
    ivy {
      url 'https://github.com/edgez-ai/organicmaps/releases/download/v0.0.5'
      patternLayout { artifact '[artifact]-[revision].[ext]' }
      metadataSources { artifact() }
      content { includeGroup 'ai.edgez.organicmaps' }
    }`;

const NODE_RESOLVER = `def resolveEdgezNode = {
  def candidates = [
    providers.gradleProperty("edgezNodeExecutable").getOrNull(),
    System.getenv("NODE_BINARY"),
    "/opt/homebrew/bin/node",
    "/usr/local/bin/node",
  ].findAll { it }
  def nvmRoot = new File(System.getProperty("user.home"), ".nvm/versions/node")
  if (nvmRoot.isDirectory()) {
    def nvmVersions = nvmRoot.listFiles()
      ?.findAll { it.isDirectory() && it.name.startsWith("v22.") }
      ?.sort { left, right -> right.name <=> left.name }
      ?.collect { new File(it, "bin/node").absolutePath } ?: []
    candidates.addAll(nvmVersions)
  }
  candidates.find { new File(it).canExecute() } ?: "node"
}
def edgezNode = resolveEdgezNode()
`;

function addOnce(source, anchor, addition, description) {
  if (source.includes(addition.trim())) return source;
  const index = source.indexOf(anchor);
  if (index < 0) throw new Error(`Cannot add ${description}; missing anchor: ${anchor}`);
  return source.replace(anchor, `${anchor}${addition}`);
}

module.exports = function withEdgezNative(config) {
  config = withAndroidManifest(config, manifestConfig => {
    const application = manifestConfig.modResults.manifest.application[0];
    application.activity = application.activity || [];
    const upsertActivity = (name, attributes) => {
      let activity = application.activity.find(item => item.$['android:name'] === name);
      if (!activity) {
        activity = { $: { 'android:name': name } };
        application.activity.push(activity);
      }
      Object.assign(activity.$, attributes);
      return activity;
    };
    const expoTask = {
      'android:process': ':expo',
      'android:taskAffinity': '${applicationId}.expo',
      'android:excludeFromRecents': 'true',
    };
    const expoRuntimeActivity = upsertActivity('.ExpoRuntimeActivity', {
      ...expoTask,
      'android:exported': 'true',
      'android:launchMode': 'singleTask',
      'android:theme': '@style/Theme.App.SplashScreen',
    });
    upsertActivity('.EmbeddedBundleActivity', {
      'android:process': ':embedded',
      'android:taskAffinity': '${applicationId}.embedded',
      'android:excludeFromRecents': 'true',
      'android:exported': 'false',
      'android:launchMode': 'singleTop',
      'android:theme': '@style/AppTheme',
    });

    // Development-client and custom app links must enter the isolated Expo
    // process. MainActivity intentionally retains only MAIN/LAUNCHER so a
    // remote Metro bundle can never replace the built-in DevTools home.
    const mainActivity = application.activity.find(
      item => item.$['android:name'] === '.MainActivity',
    );
    if (mainActivity?.['intent-filter']) {
      const hasAction = (filter, name) =>
        (filter.action || []).some(
          action => action.$['android:name'] === name,
        );
      const isViewFilter = filter =>
        hasAction(filter, 'android.intent.action.VIEW');
      const isLauncherFilter = filter =>
        hasAction(filter, 'android.intent.action.MAIN');
      const viewFilters = mainActivity['intent-filter'].filter(isViewFilter);
      const launcherFilters = mainActivity['intent-filter'].filter(isLauncherFilter);
      mainActivity['intent-filter'] = mainActivity['intent-filter'].filter(
        filter => !isViewFilter(filter) && !isLauncherFilter(filter),
      );
      mainActivity.$['android:exported'] = 'false';
      expoRuntimeActivity['intent-filter'] = [
        ...(expoRuntimeActivity['intent-filter'] || []),
        ...viewFilters,
      ];

      const nativeHomeActivity = upsertActivity(
        'ai.edgez.androiddevtools.MainActivity',
        {
          'android:exported': 'true',
          'android:launchMode': 'singleTask',
          'android:label': '@string/edgez_app_name',
          'android:theme': '@style/EdgezAppTheme',
          'tools:replace': 'android:exported',
        },
      );
      nativeHomeActivity['intent-filter'] = [
        ...(nativeHomeActivity['intent-filter'] || []),
        ...launcherFilters,
      ];
    }
    upsertActivity('expo.modules.devlauncher.launcher.DevLauncherActivity', expoTask);
    upsertActivity('expo.modules.devlauncher.compose.AuthActivity', expoTask);
    upsertActivity(
      'expo.modules.devlauncher.launcher.errors.DevLauncherErrorActivity',
      expoTask,
    );
    return manifestConfig;
  });

  config = withGradleProperties(config, gradleConfig => {
    const properties = {
      // @edgez/react-native-sdk embeds Organic Maps and therefore requires
      // Android API 26 or newer. Keep prebuild --clean aligned with the
      // committed native project.
      'android.minSdkVersion': '26',
      edgezCmakeVersion: '3.22.1',
      // The customized Expo launcher tabs live in expo-dev-launcher's debug
      // source set and depend on expo-dev-menu's debug implementation. Expo
      // disables both source sets for release unless explicitly enabled.
      'expo.devlauncher.configureInRelease': 'true',
      'expo.devmenu.configureInRelease': 'true',
    };
    for (const [key, value] of Object.entries(properties)) {
      const current = gradleConfig.modResults.find(
        item => item.type === 'property' && item.key === key,
      );
      if (current) current.value = value;
      else gradleConfig.modResults.push({ type: 'property', key, value });
    }
    return gradleConfig;
  });

  config = withSettingsGradle(config, gradleConfig => {
    let contents = addOnce(
      gradleConfig.modResults.contents,
      'pluginManagement {\n',
      NODE_RESOLVER.split('\n').map(line => line ? `  ${line}` : line).join('\n'),
      'the Node executable resolver',
    );
    contents = contents.replaceAll('commandLine("node",', 'commandLine(edgezNode,');
    gradleConfig.modResults.contents = addOnce(
      contents,
      "include ':app'",
      SETTINGS_BLOCK,
      'the EdgeZ native Gradle project',
    );
    return gradleConfig;
  });

  config = withAppBuildGradle(config, gradleConfig => {
    let contents = addOnce(
      gradleConfig.modResults.contents,
      'apply plugin: "com.facebook.react"\n',
      `\n${NODE_RESOLVER}\n`,
      'the Node executable resolver',
    );
    contents = contents.replaceAll('["node",', '[edgezNode,');
    contents = addOnce(
      contents,
      'react {',
      '\n    // EdgeZ DevTools is the built-in home, so include its JS in assembleDebug.\n    debuggableVariants = []\n    nodeExecutableAndArgs = [edgezNode]',
      'embedded EdgeZ home bundling',
    );
    contents = addOnce(
      contents,
      'dependencies {',
      "\n    implementation project(':edgez-native')",
      'the EdgeZ native dependency',
    );
    contents = addOnce(
      contents,
      "    implementation project(':edgez-native')",
      "\n    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'",
      'the EdgeZ desugaring dependency',
    );
    contents = addOnce(
      contents,
      'android {',
      `
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }`,
      'EdgeZ core-library desugaring',
    );
    // Expo signs release with the debug key by default. CI must receive a
    // genuinely unsigned APK so it can preserve one copy and sign the other.
    contents = contents.replace(
      /(\n\s*release\s*\{[\s\S]*?)\n\s*signingConfig signingConfigs\.debug/,
      '$1\n            signingConfig null',
    );
    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });

  config = withProjectBuildGradle(config, gradleConfig => {
    gradleConfig.modResults.contents = addOnce(
      gradleConfig.modResults.contents,
      "    maven { url 'https://www.jitpack.io' }",
      ORGANIC_MAPS_REPOSITORY,
      'the Organic Maps release repository',
    );
    return gradleConfig;
  });

  config = withMainApplication(config, applicationConfig => {
    let contents = applicationConfig.modResults.contents;
    contents = addOnce(
      contents,
      'import com.facebook.react.common.ReleaseLevel',
      '\nimport ai.edgez.androiddevtools.EdgezNativePackage',
      'the EdgeZ package import',
    );
    contents = addOnce(
      contents,
      'PackageList(this).packages.apply {',
      '\n          add(EdgezNativePackage())',
      'the EdgeZ React package registration',
    );
    applicationConfig.modResults.contents = contents;
    return applicationConfig;
  });

  config = withDangerousMod(config, [
    'android',
    async modConfig => {
      const sourceDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app/src/main/java/ai/edgez/androiddevtools/runtime',
      );
      fs.mkdirSync(sourceDir, { recursive: true });
      fs.writeFileSync(
        path.join(sourceDir, 'ExpoRuntimeActivity.kt'),
        `package ai.edgez.androiddevtools.runtime

import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import expo.modules.ReactActivityDelegateWrapper

class ExpoRuntimeActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    setTheme(R.style.AppTheme)
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "main"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    ReactActivityDelegateWrapper(
      this,
      BuildConfig.IS_NEW_ARCHITECTURE_ENABLED,
      object : DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled) {}
    )
}
`,
      );
      fs.writeFileSync(
        path.join(sourceDir, 'EmbeddedBundleActivity.kt'),
        `package ai.edgez.androiddevtools.runtime

import android.content.Intent
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.facebook.react.PackageList
import com.facebook.react.ReactHost
import com.facebook.react.defaults.DefaultReactHost
import com.facebook.react.interfaces.fabric.ReactSurface
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler
import ai.edgez.androiddevtools.EdgezNativePackage

/** Loads the APK's index.android.bundle without Expo Dev Client or Metro. */
@Suppress("DEPRECATION")
class EmbeddedBundleActivity : AppCompatActivity(), DefaultHardwareBackBtnHandler {
  private lateinit var surface: ReactSurface

  private val embeddedHost: ReactHost by lazy {
    DefaultReactHost.getDefaultReactHost(
      context = applicationContext,
      packageList = PackageList(application).packages.apply { add(EdgezNativePackage()) },
      jsMainModulePath = "index",
      jsBundleAssetPath = "edgez-offgrid-map.android.bundle",
      useDevSupport = false
    )
  }

  override fun onCreate(savedInstanceState: Bundle?) {
    setTheme(R.style.AppTheme)
    super.onCreate(savedInstanceState)
    surface = embeddedHost.createSurface(this, "main", null)
    setContentView(checkNotNull(surface.view) { "React surface did not create a view" })
    surface.start()
  }

  override fun onResume() {
    super.onResume()
    embeddedHost.onHostResume(this, this)
  }

  override fun onPause() {
    embeddedHost.onHostPause(this)
    super.onPause()
  }

  override fun onNewIntent(intent: Intent) {
    super.onNewIntent(intent)
    embeddedHost.currentReactContext?.onNewIntent(this, intent)
  }

  override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)
    embeddedHost.currentReactContext?.onActivityResult(this, requestCode, resultCode, data)
  }

  @Deprecated("Deprecated in Android")
  override fun onBackPressed() {
    if (!embeddedHost.onBackPressed()) {
      invokeDefaultOnBackPressed()
    }
  }

  override fun invokeDefaultOnBackPressed() {
    super.onBackPressed()
  }

  override fun onDestroy() {
    surface.stop()
    embeddedHost.onHostDestroy(this)
    super.onDestroy()
  }
}
`,
      );
      return modConfig;
    },
  ]);

  return config;
};
