const {
  withAppBuildGradle,
  withGradleProperties,
  withMainApplication,
  withSettingsGradle,
} = require('expo/config-plugins');

const SETTINGS_BLOCK = `
// @generated by withEdgezNative
include ':edgez-native'
project(':edgez-native').projectDir = new File(rootDir, '../native/edgez-android')`;

function addOnce(source, anchor, addition, description) {
  if (source.includes(addition.trim())) return source;
  const index = source.indexOf(anchor);
  if (index < 0) throw new Error(`Cannot add ${description}; missing anchor: ${anchor}`);
  return source.replace(anchor, `${anchor}${addition}`);
}

module.exports = function withEdgezNative(config) {
  config = withGradleProperties(config, gradleConfig => {
    const exists = gradleConfig.modResults.some(
      item => item.type === 'property' && item.key === 'edgezCmakeVersion',
    );
    if (!exists) {
      gradleConfig.modResults.push({
        type: 'property',
        key: 'edgezCmakeVersion',
        value: '3.22.1',
      });
    }
    return gradleConfig;
  });

  config = withSettingsGradle(config, gradleConfig => {
    gradleConfig.modResults.contents = addOnce(
      gradleConfig.modResults.contents,
      "include ':app'",
      SETTINGS_BLOCK,
      'the EdgeZ native Gradle project',
    );
    return gradleConfig;
  });

  config = withAppBuildGradle(config, gradleConfig => {
    gradleConfig.modResults.contents = addOnce(
      gradleConfig.modResults.contents,
      'dependencies {',
      '\n    implementation project(\':edgez-native\')',
      'the EdgeZ native dependency',
    );
    return gradleConfig;
  });

  config = withMainApplication(config, applicationConfig => {
    let contents = applicationConfig.modResults.contents;
    contents = addOnce(
      contents,
      'import com.facebook.react.common.ReleaseLevel',
      '\nimport ai.edgez.androiddevtools.EdgezNativePackage',
      'the EdgeZ package import',
    );
    contents = addOnce(
      contents,
      'PackageList(this).packages.apply {',
      '\n          add(EdgezNativePackage())',
      'the EdgeZ React package registration',
    );
    applicationConfig.modResults.contents = contents;
    return applicationConfig;
  });

  return config;
};
